### ISSUE TITLE
crash in exif_reader

### ISSUE THREAD

**Issue by hermanw** [RouHim/this-week-in-past#68]
[2022-12-30T12:21:42Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(Invalid)', src/exif_reader.rs:30:92
stack backtrace:
   0:     0x7f1c4d1be7a0 - <unknown>
   1:     0x7f1c4d02812e - <unknown>
   2:     0x7f1c4d198324 - <unknown>
   3:     0x7f1c4d1bf8cf - <unknown>
   4:     0x7f1c4d1bf4cf - <unknown>
   5:     0x7f1c4d1c0548 - <unknown>
   6:     0x7f1c4d1c0032 - <unknown>
   7:     0x7f1c4d1bff9c - <unknown>
   8:     0x7f1c4d1bff71 - <unknown>
   9:     0x7f1c4ce85c62 - <unknown>
  10:     0x7f1c4ce85f02 - <unknown>
  11:     0x7f1c4cfa74a4 - <unknown>
  12:     0x7f1c4cf63455 - <unknown>
  13:     0x7f1c4ceab6fb - <unknown>
  14:     0x7f1c4cf637ee - <unknown>
  15:     0x7f1c4ceab6fb - <unknown>
  16:     0x7f1c4cf637ee - <unknown>
  17:     0x7f1c4ceab6fb - <unknown>
  18:     0x7f1c4cf637ee - <unknown>
  19:     0x7f1c4cf705c2 - <unknown>
  20:     0x7f1c4ce8ceae - <unknown>
  21:     0x7f1c4d0e8468 - <unknown>
  22:     0x7f1c4d0e7dc6 - <unknown>
  23:     0x7f1c4d1c17a5 - <unknown>

**Comment by RouHim** [comment]
Thank you for the bug report. 
I'll have a look and report back in this ticker.

**Comment by RouHim** [comment]
@hermanw please test the 'next' branch. The error should be fixed there.
Greetings and a happy new year

**Comment by hermanw** [comment]
> @hermanw please test the 'next' docker tag. The error should be fixed there. Greetings and a happy new year

Thanks for the quick action. I'm using "rouhim/this-week-in-past:next", but it still crashes.

[2023-01-03T08:06:03Z INFO  this_week_in_past::scheduler] Indexing resources, this may take some time depending on the amount of resources...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(Invalid)', src/exif_reader.rs:30:92

**Comment by RouHim** [comment]
Can you please try the `test` tag. the other one was overwritten by my CI Pipeline. Sorry.

**Comment by RouHim** [comment]
Great thanks
